// AUTO-GENERATED by `npm run codegen` - do not edit.
namespace $ {

export type demo_graphql_fixture_disable_likeMutationVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type demo_graphql_fixture_disable_likeMutation = { __typename?: 'Mutation', note_like: { __typename?: 'Note', id: string, likes: number } };


export function $demo_graphql_fixture_disable_like(variables: demo_graphql_fixture_disable_likeMutationVariables, opts?: { revalidate?: boolean }): demo_graphql_fixture_disable_likeMutation {
	return $demo_graphql_request(`mutation demo_graphql_fixture_disable_like(\u0024id: ID!) {
  note_like(id: \u0024id) {
    id
    likes
  }
}`, variables, { writes: [], ...opts }) as demo_graphql_fixture_disable_likeMutation
}

}
