// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixtureDisableViewerQueryVariables = Exact<{ [key: string]: never; }>;


export type DemoFixtureDisableViewerQuery = { __typename?: 'Query', viewer: { __typename?: 'User', name: string } };


export function $demo_graphql_fixture_disable_viewer(opts?: { revalidate?: boolean }): DemoFixtureDisableViewerQuery {
	return $demo_graphql_request(`query DemoFixtureDisableViewer {
  viewer {
    name
  }
}`, undefined, { reads: [], ...opts }) as DemoFixtureDisableViewerQuery
}

}
