// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoNoteCardLikeMutationVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type DemoNoteCardLikeMutation = { __typename?: 'Mutation', note_like: { __typename?: 'Note', id: string, likes: number } };


export function $demo_note_card_like(variables: DemoNoteCardLikeMutationVariables, opts?: { revalidate?: boolean }): DemoNoteCardLikeMutation {
	return $demo_graphql_request(`mutation DemoNoteCardLike(\u0024id: ID!) {
  note_like(id: \u0024id) {
    id
    likes
  }
}`, variables, opts) as DemoNoteCardLikeMutation
}

}
