// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type demo_note_card_noteFragment = { __typename?: 'Note', id: string, title: string, body: string, likes: number, author: { __typename?: 'User', name: string } } & { ' \u0024fragmentName'?: 'demo_note_card_noteFragment' };


/** Data declared by fragment `demo_note_card_note` — spread it anywhere as `...demo_note_card_note`. */
export type $demo_note_card_note = demo_note_card_noteFragment

/** Identity accessor: turns an opaque fragment ref (masked parent data) into the typed fragment fields. */
export function $demo_note_card_note_unmask(ref: $demo_graphql_ref<demo_note_card_noteFragment>): demo_note_card_noteFragment {
	return ref as demo_note_card_noteFragment
}

}
