// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoNoteCard_noteFragment = { __typename?: 'Note', id: string, title: string, body: string, likes: number, author: { __typename?: 'User', name: string } } & { ' \u0024fragmentName'?: 'DemoNoteCard_noteFragment' };


/** Data declared by fragment `DemoNoteCard_note` — spread it anywhere as `...DemoNoteCard_note`. */
export type $demo_note_card_note = DemoNoteCard_noteFragment

/** Identity accessor: turns an opaque fragment ref (masked parent data) into the typed fragment fields. */
export function $demo_note_card_note_unmask(ref: $demo_graphql_ref<DemoNoteCard_noteFragment>): DemoNoteCard_noteFragment {
	return ref as DemoNoteCard_noteFragment
}

}
