// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoAppViewerQueryVariables = Exact<{ [key: string]: never; }>;


export type DemoAppViewerQuery = { __typename?: 'Query', viewer: { __typename?: 'User', name: string } };


export function $demo_app_viewer(): DemoAppViewerQuery {
	return $demo_graphql_request(`query DemoAppViewer {
  viewer {
    name
  }
}`) as DemoAppViewerQuery
}

}
