// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoAppNotesQueryVariables = Exact<{ [key: string]: never; }>;


export type DemoAppNotesQuery = { __typename?: 'Query', notes: Array<(
    { __typename?: 'Note', id: string }
    & { ' \u0024fragmentRefs'?: { 'DemoNoteCard_noteFragment': DemoNoteCard_noteFragment } }
  )> };


/** Spreads fragments: $demo_note_card_note */
export function $demo_app_notes(opts?: { revalidate?: boolean }): DemoAppNotesQuery {
	return $demo_graphql_request(`query DemoAppNotes {
  notes {
    id
    ...DemoNoteCard_note
  }
}

fragment DemoNoteCard_note on Note {
  id
  title
  body
  likes
  author {
    name
  }
}`, undefined, opts) as DemoAppNotesQuery
}

}
