// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type demo_app_viewerQueryVariables = Exact<{ [key: string]: never; }>;


export type demo_app_viewerQuery = { __typename?: 'Query', viewer: { __typename?: 'User', name: string } };


export function $demo_app_viewer(opts?: { revalidate?: boolean }): demo_app_viewerQuery {
	return $demo_graphql_request(`query demo_app_viewer {
  viewer {
    name
  }
}`, undefined, opts) as demo_app_viewerQuery
}

}
