// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixture_authorFragment = { __typename?: 'Note', author: { __typename?: 'User', name: string } } & { ' \u0024fragmentName'?: 'DemoFixture_authorFragment' };


/** Data declared by fragment `DemoFixture_author` — spread it anywhere as `...DemoFixture_author`. */
export type $demo_graphql_fixture_typenames_author = DemoFixture_authorFragment

/** Identity accessor: turns an opaque fragment ref (masked parent data) into the typed fragment fields. */
export function $demo_graphql_fixture_typenames_author_unmask(ref: $demo_graphql_ref<DemoFixture_authorFragment>): DemoFixture_authorFragment {
	return ref as DemoFixture_authorFragment
}

}
