// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type demo_graphql_fixture_typenames_authorFragment = { __typename?: 'Note', author: { __typename?: 'User', name: string } } & { ' \u0024fragmentName'?: 'demo_graphql_fixture_typenames_authorFragment' };


/** Data declared by fragment `demo_graphql_fixture_typenames_author` — spread it anywhere as `...demo_graphql_fixture_typenames_author`. */
export type $demo_graphql_fixture_typenames_author = demo_graphql_fixture_typenames_authorFragment

/** Identity accessor: turns an opaque fragment ref (masked parent data) into the typed fragment fields. */
export function $demo_graphql_fixture_typenames_author_unmask(ref: $demo_graphql_ref<demo_graphql_fixture_typenames_authorFragment>): demo_graphql_fixture_typenames_authorFragment {
	return ref as demo_graphql_fixture_typenames_authorFragment
}

}
