// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixtureLikeMutationVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type DemoFixtureLikeMutation = { __typename?: 'Mutation', note_like: { __typename?: 'Note', id: string, likes: number } };


export function $demo_graphql_fixture_typenames_like(variables: DemoFixtureLikeMutationVariables, opts?: { revalidate?: boolean }): DemoFixtureLikeMutation {
	return $demo_graphql_request(`mutation DemoFixtureLike(\u0024id: ID!) {
  note_like(id: \u0024id) {
    id
    likes
  }
}`, variables, { writes: ['Note'], ...opts }) as DemoFixtureLikeMutation
}

}
