// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixtureNotesQueryVariables = Exact<{ [key: string]: never; }>;


export type DemoFixtureNotesQuery = { __typename?: 'Query', notes: Array<(
    { __typename?: 'Note', id: string, likes: number }
    & { ' \u0024fragmentRefs'?: { 'DemoFixture_authorFragment': DemoFixture_authorFragment } }
  )> };


/** Spreads fragments: $demo_graphql_fixture_typenames_author */
export function $demo_graphql_fixture_typenames_notes(opts?: { revalidate?: boolean }): DemoFixtureNotesQuery {
	return $demo_graphql_request(`query DemoFixtureNotes {
  notes {
    id
    likes
    ...DemoFixture_author
  }
}

fragment DemoFixture_author on Note {
  author {
    name
  }
}`, undefined, { reads: ['Note', 'User'], ...opts }) as DemoFixtureNotesQuery
}

}
