// AUTO-GENERATED by `npm run codegen` - do not edit.
namespace $ {

export type demo_graphql_fixture_typenames_notesQueryVariables = Exact<{ [key: string]: never; }>;


export type demo_graphql_fixture_typenames_notesQuery = { __typename?: 'Query', notes: Array<(
    { __typename?: 'Note', id: string, likes: number }
    & { ' \u0024fragmentRefs'?: { 'demo_graphql_fixture_typenames_authorFragment': demo_graphql_fixture_typenames_authorFragment } }
  )> };


/** Spreads fragments: $demo_graphql_fixture_typenames_author */
export function $demo_graphql_fixture_typenames_notes(opts?: { revalidate?: boolean }): demo_graphql_fixture_typenames_notesQuery {
	return $demo_graphql_request(`query demo_graphql_fixture_typenames_notes {
  notes {
    id
    likes
    ...demo_graphql_fixture_typenames_author
  }
}

fragment demo_graphql_fixture_typenames_author on Note {
  author {
    name
  }
}`, undefined, { reads: ['Note', 'User'], ...opts }) as demo_graphql_fixture_typenames_notesQuery
}

}
