// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixtureTouchMutationVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type DemoFixtureTouchMutation = { __typename?: 'Mutation', note_like: { __typename?: 'Note', id: string, likes: number } };


export function $demo_graphql_fixture_typenames_touch(variables: DemoFixtureTouchMutationVariables, opts?: { revalidate?: boolean }): DemoFixtureTouchMutation {
	return $demo_graphql_request(`mutation DemoFixtureTouch(\u0024id: ID!) {
  note_like(id: \u0024id) {
    id
    likes
  }
}`, variables, { writes: ['Note', 'User'], ...opts }) as DemoFixtureTouchMutation
}

}
