// AUTO-GENERATED by `npm run codegen` - do not edit.
namespace $ {

export type demo_graphql_fixture_typenames_touchMutationVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type demo_graphql_fixture_typenames_touchMutation = { __typename?: 'Mutation', note_like: { __typename?: 'Note', id: string, likes: number } };


export function $demo_graphql_fixture_typenames_touch(variables: demo_graphql_fixture_typenames_touchMutationVariables, opts?: { revalidate?: boolean }): demo_graphql_fixture_typenames_touchMutation {
	return $demo_graphql_request(`mutation demo_graphql_fixture_typenames_touch(\u0024id: ID!) {
  note_like(id: \u0024id) {
    id
    likes
  }
}`, variables, { writes: ['Note', 'User'], ...opts }) as demo_graphql_fixture_typenames_touchMutation
}

}
