// AUTO-GENERATED by `npm run codegen` - do not edit.
namespace $ {

export type demo_graphql_fixture_typenames_viewerQueryVariables = Exact<{ [key: string]: never; }>;


export type demo_graphql_fixture_typenames_viewerQuery = { __typename?: 'Query', viewer: { __typename?: 'User', name: string } };


export function $demo_graphql_fixture_typenames_viewer(opts?: { revalidate?: boolean }): demo_graphql_fixture_typenames_viewerQuery {
	return $demo_graphql_request(`query demo_graphql_fixture_typenames_viewer {
  viewer {
    name
  }
}`, undefined, { reads: ['User'], ...opts }) as demo_graphql_fixture_typenames_viewerQuery
}

}
