// AUTO-GENERATED by `npm run codegen` — do not edit.
namespace $ {

export type DemoFixtureViewerQueryVariables = Exact<{ [key: string]: never; }>;


export type DemoFixtureViewerQuery = { __typename?: 'Query', viewer: { __typename?: 'User', name: string } };


export function $demo_graphql_fixture_typenames_viewer(opts?: { revalidate?: boolean }): DemoFixtureViewerQuery {
	return $demo_graphql_request(`query DemoFixtureViewer {
  viewer {
    name
  }
}`, undefined, { reads: ['User'], ...opts }) as DemoFixtureViewerQuery
}

}
